# Docker Compose configuration for AI Music Improver
# Works automatically on macOS (CPU-only) and Linux (GPU-enabled)

services:
  ai-music-improver:
    build: .
    image: ai-music-improver
    container_name: ai-music-improver
    ports:
      - "8000:8000"
    volumes:
      - ./server/uploads:/app/server/uploads
      - ./server/checkpoints:/app/server/checkpoints
    environment:
      # Relax SSL validation for npm/pip in corporate networks
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      PIP_NO_VERIFY_CERTS: "1"
      PYTHONWARNINGS: "ignore"
      DEVICE_TYPE: "${DEVICE_TYPE:-cpu}"

    # Only enable this block if you're on Linux with NVIDIA GPUs
    # Remove or comment out this section on macOS
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    # Health check (waits for FastAPI to be ready)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

